
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jiebing
 */
public class AppointmentForm extends javax.swing.JFrame{

    String[] yearArray;
    Validation valid;
    GregorianCalendar currentGreg = new GregorianCalendar();
    /**
     * Creates new form AppointmentForm
     */
    public AppointmentForm() {
        initComponents();
        loadDateArray();
        addRadioButtons();
        disableAll();
        
        cmbYear.setModel(new javax.swing.DefaultComboBoxModel(yearArray));
    }
    private void loadDateArray()
    {
        yearArray = new String[100];
        yearArray[0]= "Year";
        for(int i=0; i<100; i++)
        {
            yearArray[i] = Integer.toString(currentGreg.get(Calendar.YEAR) - i);
        }
    }
    private void disableBook()
    {
        if(txtTFN1.getText().length() == 0 || txtTFN2.getText().length() == 0 || txtTFN3.getText().length() == 0 ||
                txtSurname.getText().length() == 0 || txtFirstName.getText().length() == 0 ||
                cmbDate.getSelectedIndex()==0 || cmbMonth.getSelectedIndex()==0 || cmbYear.getSelectedIndex() == 0 ||
                cmbGender.getSelectedIndex() == 0 || txtStreetNo.getText().length() == 0 || 
                txtStreetName.getText().length() == 0 || txtSuburb.getText().length() == 0 ||
                txtPostcode.getText().length() == 0 || txtPhone.getText().length() == 0)
        {
            btnBook.setEnabled(false);
        }
        else
        {
            btnBook.setEnabled(true);
        }
    }
    
    private void addRadioButtons()
    {
        rdgCustomerType.add(rdbExistingCustomer);
        rdgCustomerType.add(rdbNewCustomer);
    }
    
    private void disableAll()
    {
        txtCustomerId.setEnabled(false); txtCustomerId.setEditable(true);
        txtSurname.setEnabled(false); txtSurname.setEditable(true);
        txtFirstName.setEnabled(false); txtFirstName.setEditable(true);
        txtTFN1.setEnabled(false); txtTFN1.setEditable(true);
        txtTFN2.setEnabled(false); txtTFN2.setEditable(true);
        txtTFN3.setEnabled(false); txtTFN3.setEditable(true);
        txtPhone.setEnabled(false); txtPhone.setEditable(true);
        cmbDate.setEnabled(false);
        cmbMonth.setEnabled(false);
        cmbYear.setEnabled(false);
        cmbGender.setEnabled(false);
        txtStreetNo.setEnabled(false); txtStreetNo.setEditable(true);
        txtStreetName.setEnabled(false); txtStreetName.setEditable(true);
        txtSuburb.setEnabled(false); txtSuburb.setEditable(true);
        txtPostcode.setEnabled(false); txtPostcode.setEditable(true);
        
        btnBook.setEnabled(false);
        btnCheck.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdgCustomerType = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCustomerId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTFN1 = new javax.swing.JTextField();
        txtTFN2 = new javax.swing.JTextField();
        txtTFN3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtSurname = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtStreetNo = new javax.swing.JTextField();
        txtStreetName = new javax.swing.JTextField();
        txtSuburb = new javax.swing.JTextField();
        txtPostcode = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        cmbDate = new javax.swing.JComboBox();
        cmbMonth = new javax.swing.JComboBox();
        cmbYear = new javax.swing.JComboBox();
        btnBook = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cmbAvailableTime = new javax.swing.JComboBox();
        lblDisplay = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        cmbGender = new javax.swing.JComboBox();
        btnCheck = new javax.swing.JButton();
        rdbExistingCustomer = new javax.swing.JRadioButton();
        rdbNewCustomer = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Customer Id");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("Appointments");

        jLabel3.setText("TFN");

        txtTFN1.setToolTipText("");
        txtTFN1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTFN1KeyTyped(evt);
            }
        });

        txtTFN2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTFN2KeyTyped(evt);
            }
        });

        txtTFN3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTFN3KeyTyped(evt);
            }
        });

        jLabel4.setText(" - ");

        jLabel5.setText(" - ");

        jLabel6.setText("Surname");

        jLabel7.setText("First name");

        jLabel8.setText("DOB");

        jLabel9.setText("Gender");

        jLabel10.setText("Street No.");

        jLabel11.setText("Street name");

        jLabel12.setText("Suburb");

        jLabel13.setText("Postcode");

        jLabel14.setText("Phone No.");

        txtSurname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSurnameKeyTyped(evt);
            }
        });

        txtFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFirstNameKeyTyped(evt);
            }
        });

        txtStreetNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStreetNoKeyTyped(evt);
            }
        });

        txtStreetName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStreetNameKeyTyped(evt);
            }
        });

        txtSuburb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSuburbKeyTyped(evt);
            }
        });

        txtPostcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPostcodeKeyTyped(evt);
            }
        });

        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPhoneKeyTyped(evt);
            }
        });

        cmbDate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Date", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cmbDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDateActionPerformed(evt);
            }
        });

        cmbMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        cmbMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMonthActionPerformed(evt);
            }
        });

        cmbYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1900" }));
        cmbYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbYearActionPerformed(evt);
            }
        });

        btnBook.setText("Book");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onBook(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onExit(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClear(evt);
            }
        });

        jLabel17.setText("Booking");

        jLabel18.setText("Available times");

        cmbAvailableTime.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Time slots", "Item 2", "Item 3", "Item 4" }));

        cmbGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gender", "Male", "Female" }));
        cmbGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGenderActionPerformed(evt);
            }
        });

        btnCheck.setText("Check");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCheck(evt);
            }
        });

        rdbExistingCustomer.setText("Existing Customer");
        rdbExistingCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickExisting(evt);
            }
        });

        rdbNewCustomer.setText("New Customer");
        rdbNewCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickNew(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(43, 43, 43)
                                .addComponent(txtTFN1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTFN2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTFN3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel12))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtSuburb, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel13)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtPostcode, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtStreetNo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(56, 56, 56)
                                            .addComponent(jLabel11)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(cmbDate, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(cmbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cmbYear, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addGap(18, 18, 18)
                                    .addComponent(cmbAvailableTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblDisplay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnExit)
                                            .addGap(64, 64, 64)
                                            .addComponent(btnClear))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel14)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(54, 54, 54)
                                    .addComponent(btnBook)))
                            .addComponent(rdbExistingCustomer)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCheck))
                            .addComponent(rdbNewCustomer)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(rdbExistingCustomer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdbNewCustomer)
                        .addGap(18, 18, 18)))
                .addGap(20, 20, 20)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCheck))
                    .addComponent(jLabel1))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTFN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTFN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTFN3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtStreetNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtSuburb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtPostcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cmbAvailableTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBook)
                    .addComponent(btnExit)
                    .addComponent(btnClear))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onExit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onExit
        this.dispose();
    }//GEN-LAST:event_onExit

    private void onBook(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onBook
        valid = new Validation();
        if(!valid.isNumeric(txtTFN1.getText()) || !valid.isNumeric(txtTFN2.getText()) || !valid.isNumeric(txtTFN3.getText()))
        {
            JOptionPane.showMessageDialog(null, "Please enter a numeric value for tax file number");
        }
        else if(!valid.isName(txtSurname.getText()) || !valid.isName(txtFirstName.getText()))
        {
            JOptionPane.showMessageDialog(null, "Please enter valid names");
        }
        else if(cmbDate.getSelectedIndex() == 0 || cmbMonth.getSelectedIndex() == 0 || cmbYear.getSelectedIndex() ==0)
        {
            JOptionPane.showMessageDialog(null, "Please complete DOB");
        }
        else if(cmbGender.getSelectedIndex() == 0)
        {
            JOptionPane.showMessageDialog(null, "Please select a gender");
        }
        else if(!valid.isName(txtStreetName.getText()))
        {
            JOptionPane.showMessageDialog(null, "Please enter a proper street name");
        }
        else if(!valid.isName(txtSuburb.getText()))
        {
            JOptionPane.showMessageDialog(null, "Please enter a proper suburb");
        }
        else if(!valid.isNumeric(txtPostcode.getText()))
        {
            JOptionPane.showMessageDialog(null, "Please enter a numeric value for Post code");
        }
        else if(!valid.isNumeric(txtPhone.getText()))
        {
            JOptionPane.showMessageDialog(null, "Please enter a numeric value for phone number");
        }
        else
        {
            String tfn = txtTFN1.getText() + "-" + txtTFN2.getText() + "-" + txtTFN3.getText();
            String surname = txtSurname.getText();
            String firstName = txtFirstName.getText();
            Calendar cal = Calendar.getInstance();
            cal.set(Integer.parseInt(cmbYear.getSelectedItem().toString()), cmbMonth.getSelectedIndex(), cmbDate.getSelectedIndex());
            Date dob = cal.getTime();
            char gender;
            if(cmbGender.getSelectedIndex() == 1)
            {
                gender = 'm';
            }
            else
            {
                gender = 'f';
            }
            String streetNo = txtStreetNo.getText();
            String streetName = txtStreetName.getText();
            String suburb = txtSuburb.getText();
            String postcode = txtPostcode.getText();
            String phone = txtPhone.getText();

            clsName name = new clsName(surname, firstName);
            clsAddress address = new clsAddress(streetNo, streetName, suburb, postcode);

            clsCustomer customer = new clsCustomer(tfn, name, dob, gender, phone, address);
            GlobalVar.customerList.add(customer);
            
            customer.addToDatabase();

            //TaxDatabase data = new TaxDatabase();
            //data.addCustomer(tfn, surname, firstName, dob, phone, gender, streetNo, streetName, suburb, postcode);
        }
    }//GEN-LAST:event_onBook

    private void onClear(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onClear
        txtCustomerId.setText("");
        txtTFN1.setText(""); txtTFN2.setText(""); txtTFN3.setText("");
        txtSurname.setText("");
        txtFirstName.setText("");
        cmbDate.setSelectedIndex(0);
        cmbMonth.setSelectedIndex(0);
        cmbYear.setSelectedIndex(0);
        cmbGender.setSelectedIndex(0);
        txtStreetNo.setText("");
        txtStreetName.setText("");
        txtSuburb.setText("");
        txtPostcode.setText("");
        txtPhone.setText("");
        cmbAvailableTime.setSelectedIndex(0);
    }//GEN-LAST:event_onClear

    private void txtTFN1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTFN1KeyTyped
        if(txtTFN1.getText().length() == 2)
        {
            txtTFN2.requestFocus();
        }
        disableBook();
    }//GEN-LAST:event_txtTFN1KeyTyped

    private void txtTFN2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTFN2KeyTyped
        if(txtTFN2.getText().length() == 2)
        {
            txtTFN3.requestFocus();
        }
        disableBook();
    }//GEN-LAST:event_txtTFN2KeyTyped

    private void txtTFN3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTFN3KeyTyped
        if(txtTFN3.getText().length() == 2)
        {
            txtSurname.requestFocus();
        }
        disableBook();
    }//GEN-LAST:event_txtTFN3KeyTyped

    private void onClickExisting(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onClickExisting
        disableAll();
        txtCustomerId.setEnabled(true); txtCustomerId.setEditable(true); txtCustomerId.requestFocus(true);
        
        //btnBook.setEnabled(false);
        btnCheck.setEnabled(true);
    }//GEN-LAST:event_onClickExisting

    private void onClickNew(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onClickNew
        disableAll();
        
        txtTFN1.setEnabled(true); txtTFN1.requestFocus(true);
        txtTFN2.setEnabled(true);
        txtTFN3.setEnabled(true);
        txtSurname.setEnabled(true);
        txtFirstName.setEnabled(true);
        txtPhone.setEnabled(true);
        cmbDate.setEnabled(true);
        cmbMonth.setEnabled(true);
        cmbYear.setEnabled(true);
        cmbGender.setEnabled(true);
        txtStreetNo.setEnabled(true);
        txtStreetName.setEnabled(true);
        txtSuburb.setEnabled(true);
        txtPostcode.setEnabled(true);
    }//GEN-LAST:event_onClickNew

    private void onCheck(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onCheck
        valid = new Validation();
        if(!valid.isNumeric(txtCustomerId.getText()))
        {
            JOptionPane.showMessageDialog(null, "Please enter a numerical value");
        }
        else
        {
            txtSurname.setEnabled(true); txtSurname.setEditable(false);
            txtFirstName.setEnabled(true); txtFirstName.setEditable(false);
            txtTFN1.setEnabled(true); txtTFN1.setEditable(false);
            txtTFN2.setEnabled(true); txtTFN2.setEditable(false);
            txtTFN3.setEnabled(true); txtTFN3.setEditable(false);
            txtPhone.setEnabled(true); txtPhone.setEditable(false);
            cmbDate.setEnabled(true); cmbDate.setEditable(false);
            cmbMonth.setEnabled(true); cmbMonth.setEditable(false);
            cmbYear.setEnabled(true); cmbYear.setEditable(false);
            cmbGender.setEnabled(true); cmbGender.setEditable(false);
            txtStreetNo.setEnabled(true); txtStreetNo.setEditable(false);
            txtStreetName.setEnabled(true); txtStreetName.setEditable(false);
            txtSuburb.setEnabled(true); txtSuburb.setEditable(false);
            txtPostcode.setEnabled(true); txtPostcode.setEditable(false);

            clsCustomer customer;
            boolean exists = false;

            for(int i = 0; i <GlobalVar.customerList.size(); i++)
            {
                customer = (clsCustomer) GlobalVar.customerList.get(i);
                if(Integer.parseInt(txtCustomerId.getText()) == customer.getCustomerId())
                {
                    exists = true;
                    String tfn = customer.getTfn();
                    txtTFN1.setText(tfn.substring(0, 3));
                    txtTFN2.setText(tfn.substring(4, 7));
                    txtTFN3.setText(tfn.substring(8, 11));
                    clsName name = customer.getName();
                    txtSurname.setText(name.getSurname());
                    txtFirstName.setText(name.getFirstName());
                    Date date = customer.getDob();
                    GregorianCalendar greg = new GregorianCalendar();
                    greg.setTime(date);
                    cmbDate.setSelectedIndex(greg.get(Calendar.DATE));
                    cmbMonth.setSelectedIndex(greg.get(Calendar.MONTH) + 1);
                    cmbYear.setSelectedIndex(currentGreg.get(Calendar.YEAR) - greg.get(Calendar.YEAR));
                    int genderIndex;
                    if(customer.getGender() == 'M')
                    {
                        genderIndex = 1;
                    }
                    else
                    {
                        genderIndex = 2;
                    }
                    cmbGender.setSelectedIndex(genderIndex);
                    
                    clsAddress address = customer.getAddress();
                    txtStreetNo.setText(address.getStreetNo());
                    txtStreetName.setText(address.getStreetName());
                    txtSuburb.setText(address.getSuburb());
                    txtPostcode.setText(address.getPostCode());
                    
                    txtPhone.setText(customer.getPhone());
                    
                    System.out.println("Date: " + greg.get(Calendar.DATE) + "/n"
                    + "Month: " + greg.get(Calendar.MONTH) + "/n"
                    + "Year: " + greg.get(Calendar.YEAR));
                }
            }
            if(exists == false)
            {
                JOptionPane.showMessageDialog(null, "There is no such customer");
            }
        }
    }//GEN-LAST:event_onCheck

    private void txtSurnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSurnameKeyTyped
        disableBook();
    }//GEN-LAST:event_txtSurnameKeyTyped

    private void txtFirstNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstNameKeyTyped
        disableBook();
    }//GEN-LAST:event_txtFirstNameKeyTyped

    private void txtStreetNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStreetNoKeyTyped
        disableBook();
    }//GEN-LAST:event_txtStreetNoKeyTyped

    private void txtStreetNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStreetNameKeyTyped
        disableBook();
    }//GEN-LAST:event_txtStreetNameKeyTyped

    private void txtSuburbKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSuburbKeyTyped
        disableBook();
    }//GEN-LAST:event_txtSuburbKeyTyped

    private void txtPostcodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPostcodeKeyTyped
        disableBook();
    }//GEN-LAST:event_txtPostcodeKeyTyped

    private void txtPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyTyped
        disableBook();
    }//GEN-LAST:event_txtPhoneKeyTyped

    private void cmbDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDateActionPerformed
        disableBook();
    }//GEN-LAST:event_cmbDateActionPerformed

    private void cmbMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMonthActionPerformed
        disableBook();
    }//GEN-LAST:event_cmbMonthActionPerformed

    private void cmbYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbYearActionPerformed
        disableBook();
    }//GEN-LAST:event_cmbYearActionPerformed

    private void cmbGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGenderActionPerformed
        disableBook();
    }//GEN-LAST:event_cmbGenderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppointmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppointmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppointmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppointmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppointmentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JComboBox cmbAvailableTime;
    private javax.swing.JComboBox cmbDate;
    private javax.swing.JComboBox cmbGender;
    private javax.swing.JComboBox cmbMonth;
    private javax.swing.JComboBox cmbYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblDisplay;
    private javax.swing.JRadioButton rdbExistingCustomer;
    private javax.swing.JRadioButton rdbNewCustomer;
    private javax.swing.ButtonGroup rdgCustomerType;
    private javax.swing.JTextField txtCustomerId;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPostcode;
    private javax.swing.JTextField txtStreetName;
    private javax.swing.JTextField txtStreetNo;
    private javax.swing.JTextField txtSuburb;
    private javax.swing.JTextField txtSurname;
    private javax.swing.JTextField txtTFN1;
    private javax.swing.JTextField txtTFN2;
    private javax.swing.JTextField txtTFN3;
    // End of variables declaration//GEN-END:variables
}
